{
 "title": "Metro Timetable",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Heap Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\"}",
     "legendFormat": "Used - {{id}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\", namespace=\"$namespace\"}",
     "legendFormat": "commited - {{id}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Parse timetable", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Timetable Parse p95 Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(create_cache_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Create Cache"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(file_parse_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "File parse"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(create_releationship_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Create relationship"
    }
   ]
  },
  {
   "title": "Timetable Parse p99 Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(create_cache_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Create Cache"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(file_parse_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "File parse"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(create_releationship_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "Create relationship"
    }
   ]
  },
  {
   "title": "Timetable Parse Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(create_cache_seconds_max{namespace=\"$namespace\"}[$__rate_interval]))\n/\n(rate(create_cache_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Create Cache"
    },
    {
     "expr": "(rate(file_parse_seconds_max{namespace=\"$namespace\"}[$__rate_interval]))\n/\n(rate(file_parse_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "File parse"
    },
    {
     "expr": "(rate(create_releationship_seconds_max{namespace=\"$namespace\"}[$__rate_interval]))\n/\n(rate(create_releationship_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Create relationship"
    }
   ]
  },
  { "title": "Station query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Station Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(station_query_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(station_query_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(station_query_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "JVM Heap Memory Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Heap Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Heap Commited Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\", namespace=\"$namespace\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Heap Max  Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\", namespace=\"$namespace\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Rate (req/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Average response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(http_server_requests_seconds_sum{namespace=\"$namespace\"}[$__rate_interval]))\n/\n(rate(http_server_requests_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "JVM Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "GC Pause Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "GC Avg Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\"}[$__rate_interval])\n/\nrate(jvm_gc_pause_seconds_count{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Non-Heap Memory (Metaspace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\", namespace=\"$namespace\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=\"$namespace\"}",
     "legendFormat": "Process CPU"
    },
    {
     "expr": "system_cpu_usage{namespace=\"$namespace\"}",
     "legendFormat": "System CPU"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"$namespace\"}",
     "legendFormat": "Live Threads"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{namespace=\"$namespace\"}",
     "legendFormat": "Loaded Classes"
    }
   ]
  }
 ]
}